#!/bin/sh
# Announcement message skelton
#
branch=${1?branch}
previous=${2?previous}
commit=${3-"$1"}

relname=$(git describe "$commit") &&
vername=$(expr "$relname" : 'v\(.*\)') || exit $?

git rev-parse --verify "$previous" >/dev/null || exit $?

case "$branch" in
maint)
	kind="The latest maintenance release" ;;
mainto/* | maint-[0-9]*)
	kind="An maintenance release" ;;
master)
	kind="The latest feature release" ;;
esac

case "$vername" in
*-rc[0-9]*)
	rpmroot=testing
	vername=$(echo "$vername" | tr "-" ".")
	kind="A release candidate"
	for_testing=" for testing"
	;;
*)
	for_testing=
	rpmroot="RPMS/$arch"
	;;
esac

echo "To: git@vger.kernel.org"
Meta/ProjectContact -b
echo "Subject: [ANNOUNCE] GIT $vername
"

fmt -70 <<EOF
$kind GIT $vername is available at the usual places$for_testing:

  http://www.kernel.org/pub/software/scm/git/

  git-$vername.tar.{gz,bz2}			(source tarball)
  git-htmldocs-$vername.tar.{gz,bz2}		(preformatted docs)
  git-manpages-$vername.tar.{gz,bz2}		(preformatted docs)

The RPM binary packages for a few architectures are found in:

  $rpmroot/git-*-$vername-1.fc9.\$arch.rpm	(RPM)

BLURB HERE BLURB HERE BLURB HERE

----------------------------------------------------------------

Changes since $previous are as follows:

EOF

git log --no-merges "$previous".."$branch" |
git shortlog

