#!/bin/sh
bindir="$1"
gitexecdir="$2"
gitcmd="$3"
if test "$bindir" != "$gitexecdir" -a -x "$gitcmd"
then
	echo
	echo "!! You have installed git-* commands to new gitexecdir."
	echo "!! Old version git-* commands still remain in bindir."
	echo "!! Mixing two versions of Git will lead to problems."
	echo "!! Please remove old version commands in bindir now."
	echo
fi
