/* Automatically generated by generate-cmdlist.sh */
struct cmdname_help
{
    char name[16];
    char help[80];
};

static struct cmdname_help common_cmds[] = {
  {"add", "Add file contents to the index"},
  {"bisect", "Find by binary search the change that introduced a bug"},
  {"branch", "List, create, or delete branches"},
  {"checkout", "Checkout a branch or paths to the working tree"},
  {"clone", "Clone a repository into a new directory"},
  {"commit", "Record changes to the repository"},
  {"diff", "Show changes between commits, commit and working tree, etc"},
  {"fetch", "Download objects and refs from another repository"},
  {"grep", "Print lines matching a pattern"},
  {"init", "Create an empty git repository or reinitialize an existing one"},
  {"log", "Show commit logs"},
  {"merge", "Join two or more development histories together"},
  {"mv", "Move or rename a file, a directory, or a symlink"},
  {"pull", "Fetch from and merge with another repository or a local branch"},
  {"push", "Update remote refs along with associated objects"},
  {"rebase", "Forward-port local commits to the updated upstream head"},
  {"reset", "Reset current HEAD to the specified state"},
  {"rm", "Remove files from the working tree and from the index"},
  {"show", "Show various types of objects"},
  {"status", "Show the working tree status"},
  {"tag", "Create, list, delete or verify a tag object signed with GPG"},
};
