#!/bin/sh

: ${asof=${1-now}}

: ${lasttag=$(
	git tag --list 'v*.0' --sort=version:tag | tail -n 1
  )}

for r in "$lasttag..master@{$asof}" \
	"master@{$asof}..next@{$asof}" \
	"master@{$asof}..seen@{$asof}"
do
	echo "$r	$(git rev-list --count --no-merges $r)"
done
