#!/bin/sh

: ${J='-l 4 -j'}
G=/pub/software/scm/git &&

HERE=$(git symbolic-ref HEAD) || exit 1
THIS=$(git describe HEAD)

d='
MAN_BASE_URL="http://www.kernel.org/pub/software/scm/git/docs/"
ASCIIDOC_NO_ROFF=YesPlease
ASCIIDOC8=YesPlease
BLK_SHA1=YesPlease
GNU_ROFF=YesPlease'

rm -f version
case `hostname` in
hera.kernel.org)
	narch='x86_64 i386 i686'
	arch=x86_64 ;;
wing-fc*|fc*.siamese.dyndns.org|fc*)
	eval $(rpm --showrc | sed -ne '
		s/^-14: dist[ 	]*\./dist=/p
		s/^-11= _target_cpu[ 	]*/arch=/p
	') &&
	test -n "$dist" && test -n "$arch" || exit 1
	;;
*)	echo >&2 "What are you talking about???"
	exit 1 ;;
esac &&
: >./:all.log &&
echo "* Building $THIS" &&
make $J git >./:all.log 2>&1 &&
V=`./git --version | sed -e 's/git version //'` &&
NEEDS_CRYPTO_WITH_SSL=YesPlease make $d rpm >>./:all.log 2>&1 &&
case "$narch" in
'')
	# This is not the primary build machine.
	status=$?
	case "$status" in
	0)
		echo >&2 "Done -- move RPMS to the master machine."
		(
			cd "$HOME/rpms/" &&
			tar cf "TARBALL/$V.$arch.$dist.tar" \
				RPMS/$arch/*-$V-*.$dist.$arch.rpm &&
			ls -ld $HOME/rpms/TARBALL/$V.$arch.$dist.tar
		) &&
		make clean
		;;
	?)
		echo >&2 "Failed with status $status"
		;;
	esac
	exit $status ;;
*)
	make $d dist-doc >>./:all.log 2>&1 &&
	ln -f git-$V.tar.gz $G/. &&
	ln -f git-htmldocs-$V.tar.gz git-manpages-$V.tar.gz $G/.
	;;
esac >>./:all.log 2>&1 &&
case "$V" in
*.rc[0-9]* | *-rc[0-9]*)
	mkdir -p $G/testing &&
	for a in $narch
	do
		for rr in $HOME/rpms/RPMS/$a/*-$V-*.$a.rpm
		do
			test -f "$rr" || continue
			ln -f "$rr" $G/testing/.
		done
	done &&
	ln -f $HOME/rpms/SRPMS/git-$V-*.src.rpm $G/testing/.
	;;
*)
	mkdir -p $G/RPMS/$arch $G/RPMS/SRPMS &&
	for a in $narch
	do
		mkdir -p "$G/RPMS/$a" &&
		for rr in $HOME/rpms/RPMS/$a/*-$V-*.$a.rpm
		do
			test -f "$rr" || continue
			ln -f "$rr" $G/RPMS/$a/.
		done
	done &&
	ln -f $HOME/rpms/SRPMS/git-$V-*.src.rpm $G/RPMS/SRPMS/. &&
	{
		# I do not know how it exits, and I do not care much.
		for a in $narch
		do
			/usr/local/bin/yummy $G/RPMS/$a
		done
		/usr/local/bin/yummy $G/RPMS/SRPMS
		:
	} >>./:all.log 2>&1 ;;
esac &&
make clean
