#!/bin/sh

J=
# J='-l 4 -j'
nodo=echo

cd $HOME/git &&
make clean &&
git reset --hard &&
make clean &&
git checkout master &&
git pull . origin &&
make clean &&

case "$1" in
'')
	make $J install &&
	make test &&
	make clean &&
	git checkout pu &&
	make $J clean &&
	make test clean
	;;
maint | master)
	G=/pub/software/scm/git &&

	git checkout "$1" &&
	make rpm >./:rpm.log 2>&1 &&
	make $J git &&
	V=$(./git --version | sed -e 's/git version //') &&
	$nodo ln git-$V.tar.gz $G/. &&
	D=`pwd` &&
	M="git-man-pages-$V" &&
	H="git-html-pages-$V" &&
	rm -rf "$M" "$H" &&
	make man1="$D/$M/man1" man7="$D/$M/man7" WEBDOC_DEST="$D/$H" \
		-C Documentation install install-webdoc >./:doc.log 2>&1 &&
	$nodo tar zcf "$G/$M".tar.gz "$M" &&
	$nodo tar zcf "$G/$H".tar.gz "$H" &&
	rm -fr "$M" "$H" ./:rpm.log ./:doc.log &&
	make clean &&

	$nodo ln $HOME/rpms/RPMS/i386/git*-$V-* $G/RPMS/i386/. &&
	$nodo ln $HOME/rpms/SRPMS/git-$V-* $G/RPMS/SRPMS/.
	;;
esac || exit $?

git checkout master
