#!/bin/sh

echo "/* Automatically generated by generate-configlist.sh */"
echo

print_config_list () {
	cat <<EOF
static const char *config_name_list[] = {
EOF
	grep -h '^[a-zA-Z].*\..*::$' Documentation/*config.txt Documentation/config/*.txt |
	sed '/deprecated/d; s/::$//; s/,  */\n/g' |
	sort |
<<<<<<< HEAD
<<<<<<< HEAD
	while read line
	do
		echo "	\"$line\","
	done
=======
	sed 's/^.*$/	"&",/'
>>>>>>> upstream/pu
=======
	sed 's/^.*$/	"&",/'
>>>>>>> upstream/maint
	cat <<EOF
	NULL,
};
EOF
}

echo
print_config_list
