#!/bin/sh

cmd=
path=$(dirname $0)
case "$#" in
0)	;;
*)	cmd="$1"
	shift
	test -x $path/git-$cmd-script && exec $path/git-$cmd-script "$@"
	test -x $path/git-$cmd && exec $path/git-$cmd "$@" ;;
esac

echo "Usage: git COMMAND [OPTIONS] [TARGET]"
if [ -n "$cmd" ]; then
    echo " git command '$cmd' not found: commands are:"
else
    echo " git commands are:"
fi

ls $path | sed -ne 's/^git-\(.*\)-script/  \1/p' | fmt
