#!/bin/sh
# Copyright (c) 2005 Linus Torvalds

. git-sh-setup-script || die "Not a git archive"

signed=
force=
while case "$#" in 0) break ;; esac
do
    case "$1" in
    -s)
	signed=1
	;;
    -f)
	force=1
	;;
    *)
	break
	;;
    esac
    shift
done

name="$1"
[ "$name" ] || die "I need a tag-name"
[ -e "$GIT_DIR/refs/tags/$name" ] &&
	[ "$force" ] || die "tag '$name' already exists"
shift

object=$(git-rev-parse --verify --revs-only --default HEAD "$@") || exit 1
type=$(git-cat-file -t $object) || exit 1
tagger=$(git-var GIT_COMMITTER_IDENT) || exit 1

if [ "$signed" ]; then
    ( echo "#"
      echo "# Write a tag message"
      echo "#" ) > .editmsg
    ${VISUAL:-${EDITOR:-vi}} .editmsg || exit

    grep -v '^#' < .editmsg | git-stripspace > .tagmsg

    [ -s .tagmsg ] || exit

    ( echo -e "object $object\ntype $type\ntag $name\ntagger $tagger\n"; cat .tagmsg ) > .tmp-tag
    rm -f .tmp-tag.asc .tagmsg
    gpg -bsa .tmp-tag && cat .tmp-tag.asc >> .tmp-tag
    object=$(git-mktag < .tmp-tag)
    rm -f .tmp-tag .tmp-tag.sig
fi

mkdir -p "$GIT_DIR/refs/tags"
echo $object > "$GIT_DIR/refs/tags/$name"
