#!/bin/sh
# Copyright (c) 2005 Linus Torvalds

. git-sh-setup-script || die "Not a git archive"
name="$1"
[ "$name" ] || die "I need a tag-name"

object=${2:-$(cat "$GIT_DIR"/HEAD)}
type=$(git-cat-file -t $object) || exit 1
tagger=$(git-var GIT_COMMITTER_IDENT) || exit 1

( echo "#"
  echo "# Write a tag message"
  echo "#" ) > .editmsg
${VISUAL:-${EDITOR:-vi}} .editmsg || exit

grep -v '^#' < .editmsg | git-stripspace > .tagmsg

[ -s .tagmsg ] || exit

( echo -e "object $object\ntype $type\ntag $name\ntagger $tagger\n"; cat .tagmsg ) > .tmp-tag
rm -f .tmp-tag.asc .tagmsg
gpg -bsa .tmp-tag && cat .tmp-tag.asc >> .tmp-tag
mkdir -p "$GIT_DIR/refs/tags"
git-mktag < .tmp-tag > "$GIT_DIR/refs/tags/$name"
#rm .tmp-tag .tmp-tag.sig
