#!/bin/sh
#
. git-sh-setup-script || die "Not a git archive"
. git-parse-remote "$@"
merge_name="$_remote_name"

git-fetch-script "$@" || exit 1

git-resolve-script \
	"$(cat "$GIT_DIR"/HEAD)" \
	"$(cat "$GIT_DIR"/FETCH_HEAD)" \
	"Merge $merge_name"
