#!/bin/sh
. git-sh-setup-script || die "Not a git archive"
revs=$(git-rev-parse --revs-only --default HEAD "$@")
[ "$revs" ] || die "No HEAD ref"
git-rev-list --pretty $(git-rev-parse --default HEAD "$@") | LESS=-S ${PAGER:-less}
