# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# For more details on how to configure your build environment visit
# http://www.gradle.org/configure-build-environment

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and one or more variants of dependent libraries.
# This property is enabled by default if you are using AGP 7.1 or later.

android.useNamespace=true
android.enableJetifier=true

# Org settings
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m
org.gradle.parallel=true
