#!/bin/sh

ssleep () {
	seconds=$1
	now=$(date "+%s")
	sleep $(( ((now + seconds + seconds / 4) / seconds) * seconds - now))
}

stamp () {
	Meta/V 2>/dev/null | sha1sum
}

P=previous
O=observed
while :
do
	while O=$(stamp) && test "$P" = "$O"
	do
		ssleep 300
	done
	ssleep 30
	# opts --sha256 --leaks --san
	time nice -20 Meta/Dothem -j32 --dash -- -- CC=clang; uptime; date
	P=$(stamp)
	Meta/V
done
