#!/bin/sh

R=:rendezvous
if ! test -p "$R"
then
	rm -f "$R"
	mkfifo "$R" || exit
fi

export CC=clang

while cat "$R"
do
	time nice -20 Meta/Dothem -j32 --meson CC="clang -O2" USE_ASCIIDOCTOR=
	uptime; date
	Meta/V
done

exit

ssleep () {
	seconds=$1
	now=$(date "+%s")
	sleep $(( ((now + seconds + seconds / 4) / seconds) * seconds - now))
}

stamp () {
	Meta/V 2>/dev/null | sha1sum
}

export CC=clang

P=previous
O=observed
while :
do
	while O=$(stamp) && test "$P" = "$O"
	do
		ssleep 300
	done
	ssleep 30

	time nice -20 Meta/Dothem -j32 --meson CC="clang -O2" USE_ASCIIDOCTOR=

	uptime; date
	P=$(stamp)
	Meta/V
done
