#!/bin/sh

git push repo "$@" &&
git push gph "$@" &&
git push github2 "$@" &&
git push sfjp "$@" &&
git push sf.net "$@" &&

case "$#" in
0)
	git push github "$@" ;;
*)
	echo "No push to github" ;;
esac
