#!/bin/sh

for remote in ko repo gph github2 sfjp sf.net
do
	printf "%s: " "$remote"
	git push "$remote" "$@" || exit $?
done

case "$#,$*" in
0,* | 1,-n)
	printf "github mirror: "
	git push github "$@" || exit $?
	for topic in htmldocs manpages
	do
		printf "%s: " "$topic"
		( cd ../git-$topic.git && git push "$@") || exit
	done
	;;
esac
