#!/bin/sh

# Give names of targets to use on the command line
# coccicheck is not enabled by default
default="sparse hdr-check leaks address,undefined test check-docs doc"
skip=" "
more=" "

for t
do
	case "$t" in
	-)  default= ;;
	-?*) skip="$skip${t#-} " ;;
	?*)  more="$more$t " ;;
	esac
done

set -- $default $more

for t
do
	case "$skip" in
	*" $t "*)
		echo "Skipping $t" >&2
		continue ;;
	esac

	case "$t" in
	address | undefined | address,undefined)
		SANITIZE=$t \
		Meta/Make -j16 test
		;;
	leaks)
		SANITIZE=leak \
		GIT_TEST_PASSING_SANITIZE_LEAK=true Meta/Make -j16 test
		;;
	coccicheck)
		SPATCH_FLAGS=--recursive-includes Meta/Make -j16 "$t"
		;;
	*)
		Meta/Make -j16 "$t"
		;;
	esac &&
	Meta/Make -j16 distclean >/dev/null 2>&1 || return 1
done &&
Meta/Make -j16 distclean
