#!/bin/sh

for v in maint master next pu
do
	installed=$($HOME/git-$v/bin/git version)
	version=$(expr "$installed" : '.*\.g\([0-9a-f]*\)$') ||
	version=v$(expr "$installed" : 'git version \(.*\)')

	version=$(git rev-parse --verify "$version^0" 2>/dev/null)
	revision=$(git show-ref -s --verify "refs/heads/$v")
	if test "z$version" = "z$revision"
	then
		in= out= installed=
	else
		in="[41;37m" out="[m" installed="	$installed"
	fi
	echo "$in$v$out	$(git-describe refs/heads/$v)$installed"
done
