#!/bin/sh
# Prepare "What's cooking in git.git"

master_at=$(git rev-parse --verify refs/heads/master)
next_at=$(git rev-parse --verify refs/heads/next)


cat <<EOF
From: Junio C Hamano <junkio@cox.net>
Subject: What's cooking in git.git (topics)
X-master-at: $master_at
X-next-at: $next_at
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

Here are the topics that have been cooking.  Commits prefixed
with '-' are only in 'pu' while commits prefixed with '+' are
in 'next'.  The topics list the commits in reverse chronological
order.

EOF

Meta/git-topic.perl --base=master | sed -e 's/^\*./*/'
