#!/bin/sh
# Prepare "What's in git.git"

master_at=$(git rev-parse --verify refs/heads/master)

echo "To: git@vger.kernel.org"
echo "Subject: What's in git.git"
echo "X-master-at: $master_at"

tagged=`git rev-parse --not --verify tags/sa/master`
list=`git-rev-list $tagged refs/heads/master 2>/dev/null`
if test -n "$list"
then
	echo
	echo "* The 'master' branch has these since the last announcement."
	echo
	git log $tagged heads/master | git shortlog
fi

list=`git-rev-list refs/heads/master..refs/heads/next 2>/dev/null`
if test -n "$list"
then
	echo
	echo
	echo "* The 'next' branch, in addition, has these."
	echo
	git log --no-merges refs/heads/master..refs/heads/next | git shortlog
fi

list=`git-rev-list ^refs/heads/master ^refs/heads/next refs/heads/pu 2>/dev/null`
if test -n "$list"
then
	echo
	echo
	echo "* The 'pu' branch, in addition, has these."
	echo
	git log --no-merges ^refs/heads/master ^refs/heads/next refs/heads/pu | git shortlog
fi
