#!/bin/sh
# Prepare "What's in git.git"

maint_at=$(git rev-parse --verify refs/heads/maint)
master_at=$(git rev-parse --verify refs/heads/master)
maint_was=$(git rev-parse --verify refs/hold/sa/maint)
master_was=$(git rev-parse --verify refs/hold/sa/master)

log () {
	git shortlog -w76,2,4 --no-merges "$@"
}

echo "Subject: What's in git.git (stable)"
echo "X-maint-at: $maint_at"
echo "X-master-at: $master_at"
echo "X-maint-was: $maint_was"
echo "X-master-was: $master_was"

tagged=`git rev-parse --not --verify hold/sa/maint`
list=`git rev-list $tagged refs/heads/maint 2>/dev/null`
a=
if test -n "$list"
then
	echo
	echo "* The 'maint' branch has these fixes since the last announcement."
	echo
	log $tagged heads/maint
	a='
  in addition to the above.'
else
	a=.
fi

tagged=`git rev-parse --not --verify hold/sa/master`
list=`git rev-list $tagged refs/heads/master 2>/dev/null`
if test -n "$list"
then
	echo
	echo "* The 'master' branch has these since the last announcement$a"
	echo
	log $tagged heads/master ^heads/maint
fi
