#!/bin/sh

usage () {
	echo "usage:" $@
	exit 127
}

die () {
	echo $@
	exit 128
}

failed () {
	die "unable to create new workdir '$new_workdir'!"
}

if test $# -lt 2 || test $# -gt 3
then
	usage "$0 <repository> <new_workdir> [<branch>]"
fi

orig_but=$1
new_workdir=$2
branch=$3

# want to make sure that what is pointed to has a .but directory ...
but_dir=$(cd "$orig_but" 2>/dev/null &&
  but rev-parse --but-dir 2>/dev/null) ||
  die "Not a but repository: \"$orig_but\""

case "$but_dir" in
.but)
	but_dir="$orig_but/.but"
	;;
.)
	but_dir=$orig_but
	;;
esac

# don't link to a configured bare repository
isbare=$(but --but-dir="$but_dir" config --bool --get core.bare)
if test ztrue = "z$isbare"
then
	die "\"$but_dir\" has core.bare set to true," \
		" remove from \"$but_dir/config\" to use $0"
fi

# don't link to a workdir
if test -h "$but_dir/config"
then
	die "\"$orig_but\" is a working directory only, please specify" \
		"a complete repository."
fi

# make sure the links in the workdir have full paths to the original repo
but_dir=$(cd "$but_dir" && pwd) || exit 1

# don't recreate a workdir over an existing directory, unless it's empty
if test -d "$new_workdir"
then
	if test $(ls -a1 "$new_workdir/." | wc -l) -ne 2
	then
		die "destination directory '$new_workdir' is not empty."
	fi
	cleandir="$new_workdir/.but"
else
	cleandir="$new_workdir"
fi

mkdir -p "$new_workdir/.but" || failed
cleandir=$(cd "$cleandir" && pwd) || failed

cleanup () {
	rm -rf "$cleandir"
}
siglist="0 1 2 15"
trap cleanup $siglist

# create the links to the original repo.  explicitly exclude index, HEAD and
# logs/HEAD from the list since they are purely related to the current working
# directory, and should not be shared.
for x in config refs logs/refs objects info hooks packed-refs remotes rr-cache svn
do
	# create a containing directory if needed
	case $x in
	*/*)
		mkdir -p "$new_workdir/.but/${x%/*}"
		;;
	esac

	ln -s "$but_dir/$x" "$new_workdir/.but/$x" || failed
done

# commands below this are run in the context of the new workdir
cd "$new_workdir" || failed

# copy the HEAD from the original repository as a default branch
cp "$but_dir/HEAD" .but/HEAD || failed

# the workdir is set up.  if the checkout fails, the user can fix it.
trap - $siglist

# checkout the branch (either the same as HEAD from the original repository,
# or the one that was asked for)
but checkout -f $branch
