#!/bin/sh

# Fix some commands on Windows
case $(uname -s) in
*MINGW*)
	winpath () {
		# pwd -W is the only way of getting msys to convert the path, especially mounted paths like /usr
		# since cmd /c only takes a single parameter preventing msys automatic path conversion.
		if test  "${1:~-1:1}" != "/" ; then
			echo "$1" | sed 's+/+\\+g'
		elif test -d "$1" ; then
			(cd "$1"; pwd -W) | sed 's+/+\\+g'
		elif test -d "${1%/*}" ; then
			(cd "${1%/*}"; echo "$(pwd -W)/${1##*/}") | sed 's+/+\\+g'
		else
			echo "$1" | sed -e 's+^/\([a-z]\)/+\1:/+' -e 's+/+\\+g'
		fi
	}
	# git sees Windows-style pwd
	pwd () {
		builtin pwd -W
	}
	# use mklink
	ln () {

		ln_sym_hard=/H
		ln_sym_dir=
		if test "$1" = "-s"
		then
			ln_sym_hard=
			shift
		fi
		pushd $(dirname "$2") 2>&1 > /dev/null
		builtin test -d "$1" && ln_sym_dir=/D
		popd > /dev/null 2> /dev/null
		cmd /c "mklink ${ln_sym_hard}${ln_sym_dir} \"$(winpath "$2")\" \"$(winpath "$1")\">/dev/null " 2>/dev/null
	}

	test () {
		case "$1" in
			-h)
				test_file=$(cmd /c "@dir /b/a:l \"$(winpath "${2}")\" 2> nul" )
				builtin test -n "${test_file}"
			;;
		*) builtin test "$@";;
		esac
	}
esac

usage () {
	echo "usage:" $@
	exit 127
}

die () {
	echo $@
	exit 128
}

if test $# -lt 2 || test $# -gt 3
then
	usage "$0 <repository> <new_workdir> [<branch>]"
fi

orig_git=$1
new_workdir=$2
branch=$3

# want to make sure that what is pointed to has a .git directory ...
git_dir=$(cd "$orig_git" 2>/dev/null &&
  git rev-parse --git-dir 2>/dev/null) ||
  die "Not a git repository: \"$orig_git\""

case "$git_dir" in
.git)
	git_dir="$orig_git/.git"
	;;
.)
	git_dir=$orig_git
	;;
esac

# don't link to a configured bare repository
isbare=$(git --git-dir="$git_dir" config --bool --get core.bare)
if test ztrue = z$isbare
then
	die "\"$git_dir\" has core.bare set to true," \
		" remove from \"$git_dir/config\" to use $0"
fi

# don't link to a workdir
if test -h "$git_dir/config"
then
	die "\"$orig_git\" is a working directory only, please specify" \
		"a complete repository."
fi

# don't recreate a workdir over an existing repository
if test -e "$new_workdir"
then
	die "destination directory '$new_workdir' already exists."
fi

# make sure the links use full paths
git_dir=$(cd "$git_dir"; pwd)

# create the workdir
mkdir -p "$new_workdir/.git" || die "unable to create \"$new_workdir\"!"

# create the links to the original repo.  explicitly exclude index, HEAD and
# logs/HEAD from the list since they are purely related to the current working
# directory, and should not be shared.
for x in config refs logs/refs objects info hooks packed-refs remotes rr-cache svn
do
	case $x in
	*/*)
		mkdir -p "$(dirname "$new_workdir/.git/$x")"
		;;
	esac
	test -e "$git_dir/$x" || mkdir "$git_dir/$x"
	ln -s "$git_dir/$x" "$new_workdir/.git/$x"
done

# now setup the workdir
cd "$new_workdir"
# copy the HEAD from the original repository as a default branch
cp "$git_dir/HEAD" .git/HEAD
# checkout the branch (either the same as HEAD from the original repository, or
# the one that was asked for)
git checkout -f $branch
