#!/bin/sh
#
# This test measures the performance of various read-tree
# and checkout operations.  It is primarily interested in
# the algorithmic costs of index operations and recursive
# tree traversal -- and NOT disk I/O on thousands of files.

test_description="Tests performance of read-tree"

. ./perf-lib.sh

test_perf_default_repo

# If the test repo was generated by ./repos/many-files.sh
# then we know something about the data shape and branches,
# so we can isolate testing to the ballast-related cummits
# and setup sparse-checkout so we don't have to populate
# the ballast files and directories.
#
# Otherwise, we make some general assumptions about the
# repo and consider the entire history of the current
# branch to be the ballast.

test_expect_success "setup repo" '
	if but rev-parse --verify refs/heads/p0006-ballast^{cummit}
	then
		echo Assuming synthetic repo from many-files.sh &&
		but branch br_base            master &&
		but branch br_ballast         p0006-ballast^ &&
		but branch br_ballast_alias   p0006-ballast^ &&
		but branch br_ballast_plus_1  p0006-ballast &&
		but config --local core.sparsecheckout 1 &&
		cat >.but/info/sparse-checkout <<-EOF
		/*
		!ballast/*
		EOF
	else
		echo Assuming non-synthetic repo... &&
		but branch br_base            $(but rev-list HEAD | tail -n 1) &&
		but branch br_ballast         HEAD^ || error "no ancestor cummit from current head" &&
		but branch br_ballast_alias   HEAD^ &&
		but branch br_ballast_plus_1  HEAD
	fi &&
	but checkout -q br_ballast &&
	nr_files=$(but ls-files | wc -l)
'

test_perf "read-tree br_base br_ballast ($nr_files)" '
	but read-tree -m br_base br_ballast -n
'

test_perf "switch between br_base br_ballast ($nr_files)" '
	but checkout -q br_base &&
	but checkout -q br_ballast
'

test_perf "switch between br_ballast br_ballast_plus_1 ($nr_files)" '
	but checkout -q br_ballast_plus_1 &&
	but checkout -q br_ballast
'

test_perf "switch between aliases ($nr_files)" '
	but checkout -q br_ballast_alias &&
	but checkout -q br_ballast
'

test_done
