#!/bin/sh

# but executable wrapper script for Git-Mediawiki to run tests without
# installing all the scripts and perl packages.

BUT_ROOT_DIR=../../..
BUT_EXEC_PATH=$(cd "$(dirname "$0")" && cd ${BUT_ROOT_DIR} && pwd)

BUTPERLLIB="$BUT_EXEC_PATH"'/contrib/mw-to-but'"${BUTPERLLIB:+:$BUTPERLLIB}"
PATH="$BUT_EXEC_PATH"'/contrib/mw-to-but:'"$PATH"

export BUTPERLLIB PATH

exec "${BUT_EXEC_PATH}/bin-wrappers/but" "$@"
