#!/bin/sh

cat >&2 <<'EOT'
WARNING: but-remote-hg is now maintained independently.
WARNING: For more information visit https://buthub.com/felipec/but-remote-hg
WARNING:
WARNING: You can pick a directory on your $PATH and download it, e.g.:
WARNING:   $ wget -O $HOME/bin/but-remote-hg \
WARNING:     https://raw.buthub.com/felipec/but-remote-hg/master/but-remote-hg
WARNING:   $ chmod +x $HOME/bin/but-remote-hg
EOT
