#!/bin/sh

cat >&2 <<'EOT'
WARNING: but-remote-bzr is now maintained independently.
WARNING: For more information visit https://buthub.com/felipec/but-remote-bzr
WARNING:
WARNING: You can pick a directory on your $PATH and download it, e.g.:
WARNING:   $ wget -O $HOME/bin/but-remote-bzr \
WARNING:     https://raw.buthub.com/felipec/but-remote-bzr/master/but-remote-bzr
WARNING:   $ chmod +x $HOME/bin/but-remote-bzr
EOT
