#!/bin/sh
#
# An test hook script to integrate with git to test fsmonitor.
#
# The hook is passed a version (currently 1) and a time in nanoseconds
# formatted as a string and outputs to stdout all files that have been
# modified since the given time. Paths must be relative to the root of
# the working tree and separated by a single NUL.
#
#echo "$0 $*" >&2

if test "$#" -ne 2
then
	echo "$0: exactly 2 arguments expected" >&2
	exit 2
fi

if test "$1" != 1
then
	echo "Unsupported core.fsmonitor hook version." >&2
	exit 1
fi

echo "/"
