#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long ();
use TAP::Harness::Archive;

Getopt::Long::Parser->new(
	config => [ qw/ pass_through / ],
)->getoptions(
	'jobs:1'    => \(my $jobs = $ENV{TEST_JOBS}),
	'archive=s' => \my $archive,
) or die "$0: Couldn't getoptions()";

TAP::Harness::Archive->new({
	jobs             => $jobs,
	archive          => $archive,
	($ENV{GIT_TEST_OPTS}
	 ? (test_args    => [ split /\s+/, $ENV{GIT_TEST_OPTS} ])
	 : ()),
	extra_properties => {},
})->runtests(@ARGV);
