#!/bin/sh

test_description='--ancestry-path'

#          D---E-------F
#         /     \       \
#    B---C---G---H---I---J
#   /                     \
#  A-------K---------------L--M
#
#  D..M                 == E F G H I J K L M
#  --ancestry-path D..M == E F H I J L M
#
#  D..M -- M.t                 == M
#  --ancestry-path D..M -- M.t == M
#
#  F...I                 == F G H I
#  --ancestry-path F...I == F H I
#
#  G..M -- G.t                 == [nothing - was dropped in "-s ours" merge L]
#  --ancestry-path G..M -- G.t == L
#  --ancestry-path --simplify-merges G^..M -- G.t == G L

BUT_TEST_DEFAULT_INITIAL_BRANCH_NAME=main
export BUT_TEST_DEFAULT_INITIAL_BRANCH_NAME

. ./test-lib.sh

test_merge () {
	test_tick &&
	but merge -s ours -m "$2" "$1" &&
	but tag "$2"
}

test_expect_success setup '
	test_cummit A &&
	test_cummit B &&
	test_cummit C &&
	test_cummit D &&
	test_cummit E &&
	test_cummit F &&
	but reset --hard C &&
	test_cummit G &&
	test_merge E H &&
	test_cummit I &&
	test_merge F J &&
	but reset --hard A &&
	test_cummit K &&
	test_merge J L &&
	test_cummit M
'

test_expect_success 'rev-list D..M' '
	test_write_lines E F G H I J K L M >expect &&
	but rev-list --format=%s D..M |
	sed -e "/^cummit /d" |
	sort >actual &&
	test_cmp expect actual
'

test_expect_success 'rev-list --ancestry-path D..M' '
	test_write_lines E F H I J L M >expect &&
	but rev-list --ancestry-path --format=%s D..M |
	sed -e "/^cummit /d" |
	sort >actual &&
	test_cmp expect actual
'

test_expect_success 'rev-list D..M -- M.t' '
	echo M >expect &&
	but rev-list --format=%s D..M -- M.t |
	sed -e "/^cummit /d" >actual &&
	test_cmp expect actual
'

test_expect_success 'rev-list --ancestry-path D..M -- M.t' '
	echo M >expect &&
	but rev-list --ancestry-path --format=%s D..M -- M.t |
	sed -e "/^cummit /d" >actual &&
	test_cmp expect actual
'

test_expect_success 'rev-list F...I' '
	test_write_lines F G H I >expect &&
	but rev-list --format=%s F...I |
	sed -e "/^cummit /d" |
	sort >actual &&
	test_cmp expect actual
'

test_expect_success 'rev-list --ancestry-path F...I' '
	test_write_lines F H I >expect &&
	but rev-list --ancestry-path --format=%s F...I |
	sed -e "/^cummit /d" |
	sort >actual &&
	test_cmp expect actual
'

# G.t is dropped in an "-s ours" merge
test_expect_success 'rev-list G..M -- G.t' '
	but rev-list --format=%s G..M -- G.t |
	sed -e "/^cummit /d" >actual &&
	test_must_be_empty actual
'

test_expect_success 'rev-list --ancestry-path G..M -- G.t' '
	echo L >expect &&
	but rev-list --ancestry-path --format=%s G..M -- G.t |
	sed -e "/^cummit /d" >actual &&
	test_cmp expect actual
'

test_expect_success 'rev-list --ancestry-path --simplify-merges G^..M -- G.t' '
	test_write_lines G L >expect &&
	but rev-list --ancestry-path --simplify-merges --format=%s G^..M -- G.t |
	sed -e "/^cummit /d" |
	sort >actual &&
	test_cmp expect actual
'

#   b---bc
#  / \ /
# a   X
#  \ / \
#   c---cb
#
# All refnames prefixed with 'x' to avoid confusion with the tags
# generated by test_cummit on case-insensitive systems.
test_expect_success 'setup criss-cross' '
	mkdir criss-cross &&
	(cd criss-cross &&
	 but init &&
	 test_cummit A &&
	 but checkout -b xb main &&
	 test_cummit B &&
	 but checkout -b xc main &&
	 test_cummit C &&
	 but checkout -b xbc xb -- &&
	 but merge xc &&
	 but checkout -b xcb xc -- &&
	 but merge xb &&
	 but checkout main)
'

# no cummits in bc descend from cb
test_expect_success 'criss-cross: rev-list --ancestry-path cb..bc' '
	(cd criss-cross &&
	 but rev-list --ancestry-path xcb..xbc > actual &&
	 test_must_be_empty actual)
'

# no cummits in repository descend from cb
test_expect_success 'criss-cross: rev-list --ancestry-path --all ^cb' '
	(cd criss-cross &&
	 but rev-list --ancestry-path --all ^xcb > actual &&
	 test_must_be_empty actual)
'

test_done
