#!/bin/sh
# Copyright (c) 2012 Felipe Contreras

# The first argument can be a url when the fetch/push command was a url
# instead of a configured remote. In this case, use a generic alias.
if test "$1" = "testbut::$2"; then
	alias=_
else
	alias=$1
fi
url=$2

dir="$BUT_DIR/testbut/$alias"

h_refspec="refs/heads/*:refs/testbut/$alias/heads/*"
t_refspec="refs/tags/*:refs/testbut/$alias/tags/*"

if test -n "$BUT_REMOTE_TESTBUT_NOREFSPEC"
then
	h_refspec=""
	t_refspec=""
fi

BUT_DIR="$url/.but"
export BUT_DIR

force=

mkdir -p "$dir"

if test -z "$BUT_REMOTE_TESTBUT_NO_MARKS"
then
	butmarks="$dir/but.marks"
	testbutmarks="$dir/testbut.marks"
	test -e "$butmarks" || >"$butmarks"
	test -e "$testbutmarks" || >"$testbutmarks"
fi

while read line
do
	case $line in
	capabilities)
		echo 'import'
		echo 'export'
		test -n "$h_refspec" && echo "refspec $h_refspec"
		test -n "$t_refspec" && echo "refspec $t_refspec"
		if test -n "$butmarks"
		then
			echo "*import-marks $butmarks"
			echo "*export-marks $butmarks"
		fi
		test -n "$BUT_REMOTE_TESTBUT_SIGNED_TAGS" && echo "signed-tags"
		test -n "$BUT_REMOTE_TESTBUT_NO_PRIVATE_UPDATE" && echo "no-private-update"
		echo 'option'
		echo 'object-format'
		echo
		;;
	list)
		echo ":object-format $(but rev-parse --show-object-format=storage)"
		but for-each-ref --format='? %(refname)' 'refs/heads/' 'refs/tags/'
		head=$(but symbolic-ref HEAD)
		echo "@$head HEAD"
		echo
		;;
	import*)
		# read all import lines
		while true
		do
			ref="${line#* }"
			refs="$refs $ref"
			read line
			test "${line%% *}" != "import" && break
		done

		if test -n "$butmarks"
		then
			echo "feature import-marks=$butmarks"
			echo "feature export-marks=$butmarks"
		fi

		if test -n "$BUT_REMOTE_TESTBUT_FAILURE"
		then
			echo "feature done"
			exit 1
		fi

		echo "feature done"
		but fast-export \
			${h_refspec:+"--refspec=$h_refspec"} \
			${t_refspec:+"--refspec=$t_refspec"} \
			${testbutmarks:+"--import-marks=$testbutmarks"} \
			${testbutmarks:+"--export-marks=$testbutmarks"} \
			$refs
		echo "done"
		;;
	export)
		if test -n "$BUT_REMOTE_TESTBUT_FAILURE"
		then
			# consume input so fast-export doesn't get SIGPIPE;
			# but would also notice that case, but we want
			# to make sure we are exercising the later
			# error checks
			while read line; do
				test "done" = "$line" && break
			done
			exit 1
		fi

		before=$(but for-each-ref --format=' %(refname) %(objectname) ')

		but fast-import \
			${force:+--force} \
			${testbutmarks:+"--import-marks=$testbutmarks"} \
			${testbutmarks:+"--export-marks=$testbutmarks"} \
			--quiet

		# figure out which refs were updated
		but for-each-ref --format='%(refname) %(objectname)' |
		while read ref a
		do
			case "$before" in
			*" $ref $a "*)
				continue ;;	# unchanged
			esac
			if test -z "$BUT_REMOTE_TESTBUT_PUSH_ERROR"
			then
				echo "ok $ref"
			else
				echo "error $ref $BUT_REMOTE_TESTBUT_PUSH_ERROR"
			fi
		done

		echo
		;;
	option\ *)
		read cmd opt val <<-EOF
		$line
		EOF
		case $opt in
		force)
			test $val = "true" && force="true" || force=
			echo "ok"
			;;
		object-format)
			test $val = "true" && object_format="true" || object_format=
			echo "ok"
			;;
		*)
			echo "unsupported"
			;;
		esac
		;;
	'')
		exit
		;;
	esac
done
