git-repo(1)
===========

NAME
----
git-repo - Retrieve information about the repository

SYNOPSIS
--------
[synopsis]
git repo info [--format=(keyvalue|nul) | -z] [--path-format=(absolute|relative)] [--all | <key>...]
git repo structure [--format=(table|keyvalue|nul) | -z]

DESCRIPTION
-----------
Retrieve information about the repository.

THIS COMMAND IS EXPERIMENTAL. THE BEHAVIOR MAY CHANGE.

COMMANDS
--------
`info [--format=(keyvalue|nul) | -z] [--all | <key>...]`::
	Retrieve metadata-related information about the current repository. Only
	the requested data will be returned based on their keys (see "INFO KEYS"
	section below).
+
The values are returned in the same order in which their respective keys were
requested. The `--all` flag requests the values for all the available keys.
+
The output format can be chosen through the flag `--format`. Two formats are
supported:
+
`keyvalue`:::
	output key-value pairs one per line using the `=` character as
	the delimiter between the key and the value. Values containing "unusual"
	characters are quoted as explained for the configuration variable
	`core.quotePath` (see linkgit:git-config[1]). This is the default.

`nul`:::
	similar to `keyvalue`, but using a newline character as the delimiter
	between the key and the value and using a NUL character after each value.
	This format is better suited for being parsed by another applications than
	`keyvalue`. Unlike in the `keyvalue` format, the values are never quoted.
+
`-z` is an alias for `--format=nul`.

`--path-format=(absolute|relative)`:::
	Controls formatting for keys in the `path` category. The default is
	`absolute`. This option may be specified multiple times; the last one
	specified takes effect.

`structure [--format=(table|keyvalue|nul) | -z]`::
	Retrieve statistics about the current repository structure. The
	following kinds of information are reported:
+
* Reference counts categorized by type
* Reachable object counts categorized by type
* Total inflated size of reachable objects by type
* Total disk size of reachable objects by type
* Largest inflated reachable object size by type
* Largest disk size of a reachable object by type
* Largest parent count among reachable commits
* Largest entry count among reachable trees
* Longest and deepest path among reachable blobs
* Deepest annotated tag chain
+
The output format can be chosen through the flag `--format`. Three formats are
supported:
+
`table`:::
	Outputs repository stats in a human-friendly table. This format may
	change and is not intended for machine parsing. This is the default
	format.

`keyvalue`:::
	Each line of output contains a key-value pair for a repository stat.
	The '=' character is used to delimit between the key and the value.
	Both aggregate metrics and per-type metrics are included.
	Values containing "unusual" characters are quoted as explained for the
	configuration variable `core.quotePath` (see linkgit:git-config[1]).

`nul`:::
	Similar to `keyvalue`, but uses a NUL character to delimit between
	key-value pairs instead of a newline. Also uses a newline character as
	the delimiter between the key and value instead of '='. Unlike the
	`keyvalue` format, values containing "unusual" characters are never
	quoted.
+
`-z` is an alias for `--format=nul`.

INFO KEYS
---------
In order to obtain values from `git repo info`, provide either individual keys
or category names. A category returns all keys within that category. For
example, `layout` returns both `layout.bare` and `layout.shallow`.

Here's a list of the available keys and the values that they return:

`layout.bare`::
	`true` if this is a bare repository, otherwise `false`.

`layout.shallow`::
	`true` if this is a shallow repository, otherwise `false`.

`object.format`::
	The object format (hash algorithm) used in the repository.

`path.common-dir`::
	The path to the common git directory.

`path.config-file`::
	The path to the `config` file in the git directory.

`path.git-dir`::
	The path to the git directory.

`path.git-prefix`::
	The path of the current working directory relative to the top-level
	directory.

`path.grafts-file`::
	The path to the `info/grafts` file.

`path.hooks-directory`::
	The path to the `hooks` directory.

`path.index-file`::
	The path to the index file.

`path.logs-directory`::
	The path to the `logs` directory.

`path.objects-directory`::
	The path to the objects directory.

`path.packed-refs-file`::
	The path to the `packed-refs` file.

`path.refs-directory`::
	The path to the `refs` directory.

`path.shallow-file`::
	The path to the `shallow` file.

`path.superproject-working-tree`::
	The path to the superproject's working tree root, or an empty string
	when the repository is not used as a submodule.

`path.toplevel`::
	The path to the top-level working tree directory, or an empty string
	for bare repositories.

`references.format`::
	The reference storage format. The valid values are:
+
include::ref-storage-format.adoc[]

EXAMPLES
--------

* Retrieves the reference format of the current repository:
+
------------
git repo info references.format
------------
+

* Retrieves whether the current repository is bare and whether it is shallow
using the `nul` format:
+
------------
git repo info --format=nul layout.bare layout.shallow
------------

SEE ALSO
--------
linkgit:git-rev-parse[1]

GIT
---
Part of the linkgit:git[1] suite
